apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats-monitor
  labels:
    release: kube-prometheus-stack-1769530217
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
  endpoints:
  - port: prometheus
    path: /metrics
