apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/cm.yaml
  - manifests/pg.yaml
  - manifests/pvc.yaml
  - manifests/http-route.yaml
  - manifests/ns.yaml
  - manifests/cronjob.yaml

images:
  - name: PROJECT/IMAGE
    newName: europe-southwest1-docker.pkg.dev/dwk-gke-485711/my-repository/the_project:3.11-7540e6cc1ac19aa85de9b71744a6ea9341c2c63d


namespace: master