events { worker_connections 1024; }

http {
  server {
    listen 80;

    location / {
      proxy_pass http://frontend:8080;
    }

    location /todos {
      proxy_pass http://backend:9090;
    }
  }
}
