name: Release application

on:
  push:
    paths:
      - log_output/**


jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: log_output


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish backend
        run: |-
          docker build --tag "ssantos94/log-output:$GITHUB_SHA" .
          docker push "ssantos94/log-output:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Use right image
        run: kustomize edit set image PROJECT/IMAGE=ssantos94/log-output:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: './log_output/kustomization.yaml'
          message: New version released ${{ github.sha }}